on:
  repository_dispatch:
    types: publish-beta

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
        ref: v2_beta
    - name: Remove .github directory, useless on 'latest-beta' branch
      run: rm -r .github
    - name: Remove branch 'latest-beta' 
      continue-on-error: true
      run: |
        git branch -d latest-beta || true
        git push origin :latest-beta
    - name: Create the new 'latest-beta' branch
      run: |
        git branch latest-beta
        git checkout latest-beta
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run enable_short_import_path
      env:
        DRY_RUN: "0"
    - name: (DEBUG) Show how the files have been moved to enable short import
      run: ls -lR
    - name: Publishing on NPM
      run: |
        if [ "$(npm show . version)" = "$VERSION" ]; then
          echo "This version is already published"
          exit 0
        fi
        if [ "$NPM_TOKEN" = "" ]; then
          echo "Can't publish on NPM, You must first create a secret called NPM_TOKEN that contains your NPM auth token. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets"
          false
        fi
        echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
        npm publish --tag beta
        rm .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        VERSION: ${{ github.event.client_payload.to_version }}
    - name: Commit changes
      run: |
        git config --local user.email "denoify_ci@github.com"
        git config --local user.name "denoify_ci"
        git add -A
        git commit -am "Enabling shorter import paths [automatic]"
    - run: git push origin latest-beta
